// Code generated by protoc-gen-zig
///! package ok
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const Person = struct {
    name: ManagedString = .Empty,
    age: i32 = 0,

    pub const _desc_table = .{
        .name = fd(1, .String),
        .age = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AddressBook = struct {
    people: ArrayList(Person),

    pub const _desc_table = .{
        .people = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
